apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeName: {{ .Values.pvc.volumeName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
