apiVersion: v2
name: site-khaddict
description: A Helm chart for site.khaddict.com
type: application
version: 0.2.0
appVersion: "stable"
home: https://github.com/khaddict/voidnode
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/site.khaddict.com
maintainers:
  - name: platform

