app: site-khaddict
namespace: site-khaddict

deployment:
  name: site-khaddict
  replicas: 3
  image: nginx:stable
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

service:
  name: site-khaddict
  type: ClusterIP
  port: 80
  targetPort: 80

probes:
  enabled: false
  liveness:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5

secret:
  name: site-khaddict

httproute:
  host: site.khaddict.lab
  gatewayName: envoy-gateway
