vault:
  auth:
    token: {{ vault_token }}
  server:
    url: https://vault.khaddict.lab:8200
  policies:
    assign:
      - 'saltmaster'
  verify: /usr/local/share/ca-certificates/voidnode.chain.crt
