vault:
  auth:
    token: {{ vault_token }}
  server:
    url: https://vault.khaddict.lab:8200
  policies:
    assign:
      - minion-isolated
  verify: /etc/ssl/certs/ca-certificates.crt
  issue:
    type: approle
    approle:
      mount: salt-minions
  metadata:
    entity:
      minion-id: "{minion}"
