# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\tBSB_Error\"O\n\x05\x45rror\x12\x1f\n\x05\x63\x61use\x18\x01 \x01(\x0e\x32\x10.BSB_Error.Cause\x12%\n\x08severity\x18\x02 \x01(\x0e\x32\x13.BSB_Error.Severity*\x1b\n\x05\x43\x61use\x12\x12\n\x0eRESOURCE_LIMIT\x10\x00*-\n\x08Severity\x12\t\n\x05\x46\x41TAL\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAUSE']._serialized_start=107
  _globals['_CAUSE']._serialized_end=134
  _globals['_SEVERITY']._serialized_start=136
  _globals['_SEVERITY']._serialized_end=181
  _globals['_ERROR']._serialized_start=26
  _globals['_ERROR']._serialized_end=105
# @@protoc_insertion_point(module_scope)
