# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\tBSB_Frame\"\xac\x01\n\x05\x46rame\x12!\n\x06screen\x18\x01 \x01(\x0e\x32\x11.BSB_Frame.Screen\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12%\n\x08\x65ncoding\x18\x04 \x01(\x0e\x32\x13.BSB_Frame.Encoding\x12,\n\x0cpixel_format\x18\x05 \x01(\x0e\x32\x16.BSB_Frame.PixelFormat\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c*J\n\x08\x45ncoding\x12\t\n\x05PLAIN\x10\x00\x12\x0e\n\nRUN_LENGTH\x10\x01\x12\x0b\n\x07\x44\x45\x46LATE\x10\x02\x12\x16\n\x12\x44\x45\x46LATE_RUN_LENGTH\x10\x03*)\n\x0bPixelFormat\x12\n\n\x06RGB888\x10\x00\x12\x06\n\x02L8\x10\x01\x12\x06\n\x02L4\x10\x02*\x1d\n\x06Screen\x12\t\n\x05\x46RONT\x10\x00\x12\x08\n\x04\x42\x41\x43K\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODING']._serialized_start=201
  _globals['_ENCODING']._serialized_end=275
  _globals['_PIXELFORMAT']._serialized_start=277
  _globals['_PIXELFORMAT']._serialized_end=318
  _globals['_SCREEN']._serialized_start=320
  _globals['_SCREEN']._serialized_end=349
  _globals['_FRAME']._serialized_start=27
  _globals['_FRAME']._serialized_end=199
# @@protoc_insertion_point(module_scope)
