# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: input.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binput.proto\x12\tBSB_Input\"Y\n\x0b\x42uttonEvent\x12!\n\x06\x62utton\x18\x01 \x01(\x0e\x32\x11.BSB_Input.Button\x12\'\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x17.BSB_Input.ButtonAction\":\n\x0bSwitchEvent\x12+\n\x08position\x18\x01 \x01(\x0e\x32\x19.BSB_Input.SwitchPosition\"\x1d\n\x0c\x45ncoderEvent\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x11\"\xa7\x01\n\nInputEvent\x12.\n\x0c\x62utton_event\x18\x01 \x01(\x0b\x32\x16.BSB_Input.ButtonEventH\x00\x12.\n\x0cswitch_event\x18\x02 \x01(\x0b\x32\x16.BSB_Input.SwitchEventH\x00\x12\x30\n\rencoder_event\x18\x03 \x01(\x0b\x32\x17.BSB_Input.EncoderEventH\x00\x42\x07\n\x05\x65vent*%\n\x06\x42utton\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x42\x41\x43K\x10\x01\x12\t\n\x05START\x10\x02*&\n\x0c\x42uttonAction\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01*G\n\x0eSwitchPosition\x12\x08\n\x04\x42USY\x10\x00\x12\n\n\x06\x43USTOM\x10\x01\x12\x07\n\x03OFF\x10\x02\x12\x08\n\x04\x41PPS\x10\x03\x12\x0c\n\x08SETTINGS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUTTON']._serialized_start=378
  _globals['_BUTTON']._serialized_end=415
  _globals['_BUTTONACTION']._serialized_start=417
  _globals['_BUTTONACTION']._serialized_end=455
  _globals['_SWITCHPOSITION']._serialized_start=457
  _globals['_SWITCHPOSITION']._serialized_end=528
  _globals['_BUTTONEVENT']._serialized_start=26
  _globals['_BUTTONEVENT']._serialized_end=115
  _globals['_SWITCHEVENT']._serialized_start=117
  _globals['_SWITCHEVENT']._serialized_end=175
  _globals['_ENCODEREVENT']._serialized_start=177
  _globals['_ENCODEREVENT']._serialized_end=206
  _globals['_INPUTEVENT']._serialized_start=209
  _globals['_INPUTEVENT']._serialized_end=376
# @@protoc_insertion_point(module_scope)
