# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from state import device_name_pb2 as state_dot_device__name__pb2
from state import brightness_pb2 as state_dot_brightness__pb2
from state import power_pb2 as state_dot_power__pb2
from state import audio_pb2 as state_dot_audio__pb2
from state import wifi_pb2 as state_dot_wifi__pb2
from state import update_pb2 as state_dot_update__pb2
from state import timezone_pb2 as state_dot_timezone__pb2
from state import matter_pb2 as state_dot_matter__pb2
from state import ble_pb2 as state_dot_ble__pb2
import frame_pb2 as frame__pb2
import timer_pb2 as timer__pb2
import input_pb2 as input__pb2
import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\tBSB_State\x1a\x17state/device_name.proto\x1a\x16state/brightness.proto\x1a\x11state/power.proto\x1a\x11state/audio.proto\x1a\x10state/wifi.proto\x1a\x12state/update.proto\x1a\x14state/timezone.proto\x1a\x12state/matter.proto\x1a\x0fstate/ble.proto\x1a\x0b\x66rame.proto\x1a\x0btimer.proto\x1a\x0binput.proto\x1a\x0b\x65rror.proto\"\x8e\x05\n\x0bStateUpdate\x12,\n\x0b\x64\x65vice_name\x18\x01 \x01(\x0b\x32\x15.BSB_State.DeviceNameH\x00\x12!\n\x05power\x18\x02 \x01(\x0b\x32\x10.BSB_State.PowerH\x00\x12+\n\nbrightness\x18\x03 \x01(\x0b\x32\x15.BSB_State.BrightnessH\x00\x12.\n\x0c\x61udio_volume\x18\x04 \x01(\x0b\x32\x16.BSB_State.AudioVolumeH\x00\x12\x1f\n\x04wifi\x18\x05 \x01(\x0b\x32\x0f.BSB_State.WifiH\x00\x12/\n\x0cupdate_state\x18\x06 \x01(\x0b\x32\x17.BSB_Update.UpdateStateH\x00\x12.\n\x0cupdate_check\x18\x07 \x01(\x0b\x32\x16.BSB_Update.CheckStateH\x00\x12\'\n\x08timezone\x18\x08 \x01(\x0b\x32\x13.BSB_State.TimezoneH\x00\x12#\n\x06matter\x18\t \x01(\x0b\x32\x11.BSB_State.MatterH\x00\x12!\n\x05\x66rame\x18\n \x01(\x0b\x32\x10.BSB_Frame.FrameH\x00\x12&\n\x05input\x18\x0b \x01(\x0b\x32\x15.BSB_Input.InputEventH\x00\x12!\n\x05timer\x18\x0c \x01(\x0b\x32\x10.BSB_Timer.TimerH\x00\x12!\n\x03\x62le\x18\r \x01(\x0b\x32\x12.BSB_State.Ble.BleH\x00\x12\x38\n\x11\x61uto_update_state\x18\x0e \x01(\x0b\x32\x1b.BSB_Update.AutoUpdateStateH\x00\x12-\n\x0etimer_profiles\x18\x0f \x01(\x0b\x32\x13.BSB_Timer.ProfilesH\x00\x42\x07\n\x05state\"s\n\x05State\x12\x11\n\ttimestamp\x18\x01 \x01(\x06\x12\'\n\x07updates\x18\x02 \x03(\x0b\x32\x16.BSB_State.StateUpdate\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x10.BSB_Error.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEUPDATE']._serialized_start=263
  _globals['_STATEUPDATE']._serialized_end=917
  _globals['_STATE']._serialized_start=919
  _globals['_STATE']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
