# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'timer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from util import json_pb2 as util_dot_json__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btimer.proto\x12\tBSB_Timer\x1a\x0futil/json.proto\"5\n\x07Profile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x04json\x18\x02 \x01(\x0b\x32\x0e.BSB_Util.Json\"0\n\x08Profiles\x12$\n\x08profiles\x18\x01 \x03(\x0b\x32\x12.BSB_Timer.Profile\"%\n\x05Timer\x12\x1c\n\x04json\x18\x01 \x01(\x0b\x32\x0e.BSB_Util.Jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=43
  _globals['_PROFILE']._serialized_end=96
  _globals['_PROFILES']._serialized_start=98
  _globals['_PROFILES']._serialized_end=146
  _globals['_TIMER']._serialized_start=148
  _globals['_TIMER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
