apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "www-khaddict.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "www-khaddict.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "www-khaddict.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Values.deployment.name }}-html
