{{- range $site := .Values.sites }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $site.name }}-khaddict-html
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "khaddict.labels" (dict "site" $site "root" $) | nindent 4 }}
data:
{{- if eq $site.name "images" }}
  default.conf: |
{{ $.Files.Get "files/images/default.conf" | indent 4 }}
{{- else }}
  default.conf: |
{{ $.Files.Get "files/shared/default.conf" | indent 4 }}
{{- end }}
  security-headers.conf: |
{{ $.Files.Get "files/shared/security-headers.conf" | indent 4 }}
  robots.txt: |
{{ $.Files.Get "files/shared/robots.txt" | indent 4 }}
{{- if $site.hasSitemap }}
  sitemap.xml: |
{{ $.Files.Get (printf "files/%s/sitemap.xml" $site.name) | indent 4 }}
{{- end }}
  security.txt: |
{{ $.Files.Get (printf "files/%s/security.txt" $site.name) | indent 4 }}
  404.html: |
{{ $.Files.Get "files/shared/404.html" | indent 4 }}
  index.html: |
{{ $.Files.Get (printf "files/%s/index.html" $site.name) | indent 4 }}
{{- end }}
