{{- $content := index .Subcharts "khaddict-com" }}
{{- range $site := .Values.sites }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $site.name }}-khaddict
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "khaddict.labels" (dict "site" $site "root" $) | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $site.replicas }}
  selector:
    matchLabels:
      {{- include "khaddict.selectorLabels" (dict "site" $site "root" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "khaddict.selectorLabels" (dict "site" $site "root" $) | nindent 8 }}
    spec:
      containers:
      - name: {{ $site.name }}-khaddict
        image: {{ $site.image.repository }}:{{ $site.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ $.Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ $.Values.service.targetPort }}
          initialDelaySeconds: {{ $site.livenessInitialDelaySeconds }}
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ $.Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: html-volume
          mountPath: /usr/share/nginx/html/fr/index.html
          subPath: fr-index.html
        - name: html-volume
          mountPath: /usr/share/nginx/html/robots.txt
          subPath: robots.txt
        {{- if $site.hasSitemap }}
        - name: html-volume
          mountPath: /usr/share/nginx/html/sitemap.xml
          subPath: sitemap.xml
        {{- end }}
        - name: html-volume
          mountPath: /usr/share/nginx/html/security.txt
          subPath: security.txt
        - name: html-volume
          mountPath: /usr/share/nginx/html/404.html
          subPath: 404.html
        - name: html-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: html-volume
          mountPath: /etc/nginx/security-headers.conf
          subPath: security-headers.conf
        {{- if eq $site.name "blog" }}
        - name: posts-volume
          mountPath: /usr/share/nginx/html/posts
        - name: posts-volume-fr
          mountPath: /usr/share/nginx/html/fr/posts
        {{- end }}
      volumes:
      - name: html-volume
        configMap:
          name: {{ $site.name }}-khaddict-html
      {{- if eq $site.name "blog" }}
      - name: posts-volume
        configMap:
          name: blog-khaddict-posts
          items:
          {{- range $path, $bytes := $content.Files.Glob "files/blog/posts/**" }}
          - key: {{ $path | replace "files/blog/posts/" "" | replace "/" "-" | quote }}
            path: {{ $path | replace "files/blog/posts/" "" }}
          {{- end }}
      - name: posts-volume-fr
        configMap:
          name: blog-khaddict-posts-fr
          items:
          {{- range $path, $bytes := $content.Files.Glob "files/blog/fr/posts/**" }}
          - key: {{ $path | replace "files/blog/fr/posts/" "" | replace "/" "-" | quote }}
            path: {{ $path | replace "files/blog/fr/posts/" "" }}
          {{- end }}
      {{- end }}
{{- end }}
