{{- range $site := .Values.sites }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $site.name }}-khaddict
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "khaddict.labels" (dict "site" $site "root" $) | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "khaddict.selectorLabels" (dict "site" $site "root" $) | nindent 6 }}
{{- end }}
