{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: Filesystem
{{- end }}
