apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisement.name }}
  namespace: {{ .Values.namespace }}
spec:
  ipAddressPools:
    - {{ .Values.ipAddressPool.name }}
