apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NEXT_PUBLIC_SITE_URL: {{ .Values.env.NEXT_PUBLIC_SITE_URL }}
  EMAIL_USER: {{ .Values.env.EMAIL_USER }}
  EMAIL_PASS: {{ .Values.env.EMAIL_PASS }}
  WEBHOOK_URL: {{ .Values.env.WEBHOOK_URL }}
  NEXT_PUBLIC_FIREBASE_API_KEY: {{ .Values.env.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: {{ .Values.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: {{ .Values.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: {{ .Values.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: {{ .Values.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: {{ .Values.env.NEXT_PUBLIC_FIREBASE_APP_ID }}
