server {
    listen 80 default_server;
    server_name website.{{ domain }};

    location = / {
        return 302 /www/;
    }

    location /www/ {
        alias /srv/khaddict-com/files/www/;
        try_files $uri $uri/ =404;
    }

    location /blog/ {
        alias /srv/khaddict-com/files/blog/;
        try_files $uri $uri/ =404;
    }

    location /projects/ {
        alias /srv/khaddict-com/files/projects/;
        try_files $uri $uri/ =404;
    }

    location /images/ {
        alias /srv/khaddict-com/files/images/;
        try_files $uri $uri/ =404;
    }
}
