apiVersion: v2
name: envoy-gateway
description: Chart for Envoy Gateway
type: application
version: 0.1.0

dependencies:
  - name: gateway-helm
    version: v1.7.1
    repository: oci://docker.io/envoyproxy
