apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.secret.name }}
