apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "blog-khaddict.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "blog-khaddict.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blog-khaddict.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        {{- if .Values.probes.enabled }}
        livenessProbe:
          {{- toYaml .Values.probes.liveness | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.probes.readiness | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: html-volume
          mountPath: /usr/share/nginx/html/robots.txt
          subPath: robots.txt
        - name: html-volume
          mountPath: /usr/share/nginx/html/security.txt
          subPath: security.txt
        - name: html-volume
          mountPath: /usr/share/nginx/html/404.html
          subPath: 404.html
        - name: html-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: html-volume
          mountPath: /etc/nginx/security-headers.conf
          subPath: security-headers.conf
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Values.deployment.name }}-html
