apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "changedetection.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "changedetection.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "changedetection.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: data
              mountPath: /datastore
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-pvc
