BUSYBAR_URL = "{{ busybar_url }}"
BUSYBAR_PIN = "{{ busybar_pin }}"
DISCORD_WEBHOOK_URL = "{{ discord_webhook_url }}"
ALERTMANAGER_TOKEN = "{{ alertmanager_token }}"
BUSYBAR_ADMIN_TOKEN = "{{ busybar_admin_token }}"
STACKSTORM_ALERT_TOKEN = "{{ stackstorm_alert_token }}"
UPTIME_KUMA_ALERT_TOKEN = "{{ uptime_kuma_alert_token }}"
