server {
    listen 80;
    server_name khaddict.com www.khaddict.com website.khaddict.com homepage.khaddict.com images.khaddict.com status.khaddict.com matomo.khaddict.com;

    return 301 https://$host$request_uri;
}
