upstream homelab_failover {
    server 10.40.0.2:443 max_fails=1 fail_timeout=10s;
    server 127.0.0.1:8443 backup;
}

map $ssl_preread_server_name $upstream {
    status.khaddict.com  127.0.0.1:4443;
    iacine.tech          10.40.0.2:443;
    www.iacine.tech      10.40.0.2:443;
    default              homelab_failover;
}

server {
    listen 443;
    ssl_preread on;
    proxy_pass $upstream;
    proxy_protocol on;
    proxy_connect_timeout 5s;
}
