apiVersion: v2
name: assets-gui
description: A Helm chart for assets-gui
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/khaddict/voidnode
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/assets-gui
maintainers:
  - name: platform
