apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-target
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.backupTarget.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backupTarget.secretKey | quote }}
  AWS_ENDPOINTS: {{ .Values.backupTarget.endpoint | quote }}
