app: homepage
namespace: homepage

deployment:
  replicas: 1
  image: ghcr.io/gethomepage/homepage:latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

service:
  name: homepage
  type: ClusterIP
  port: 3000
  targetPort: http
  protocol: TCP

probes:
  enabled: false
  liveness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5

secret:
  name: homepage

service_account:
  name: homepage

config_map:
  name: homepage

cluster_role:
  name: homepage

cluster_role_binding:
  name: homepage

httproute:
  host: homepage.khaddict.lab
  gatewayName: envoy-gateway

services:
  pve:
    password: <path:kv/data/kubernetes/homepage#homepage_pve_token>
  argocd:
    password: <path:kv/data/kubernetes/homepage#homepage_argocd_token>
  pbs:
    password: <path:kv/data/kubernetes/homepage#homepage_pbs_token>
  changedetection:
    password: <path:kv/data/kubernetes/homepage#homepage_changedetection_token>
  grafana:
    password: <path:kv/data/kubernetes/homepage#homepage_grafana_password>
  opnsense:
    password: <path:kv/data/kubernetes/homepage#homepage_opnsense_password>
    username: <path:kv/data/kubernetes/homepage#homepage_opnsense_username>
