namespace: longhorn-system

httproute:
  host: longhorn.khaddict.lab
  gatewayName: envoy-gateway

longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn
    defaultReplicaCount: 2

  persistence:
    defaultClassReplicaCount: 2
