app: www-khaddict
namespace: www-khaddict

deployment:
  name: www-khaddict
  replicas: 3
  image: nginx:stable
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

service:
  name: www-khaddict
  type: ClusterIP
  port: 80
  targetPort: 80

secret:
  name: www-khaddict

httproute:
  host: www.khaddict.lab
  gatewayName: envoy-gateway
