apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "remark42.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "remark42.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "remark42.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.probes.enabled }}
        livenessProbe:
          {{- toYaml .Values.probes.liveness | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.probes.readiness | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /srv/var
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-pvc
      {{- end }}
