apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REMARK_URL: {{ .Values.env.REMARK_URL | quote }}
  SITE: {{ .Values.env.SITE | quote }}
  AUTH_GITHUB_CID: {{ .Values.env.AUTH_GITHUB_CID | quote }}
  AUTH_GITHUB_CSEC: {{ .Values.env.AUTH_GITHUB_CSEC | quote }}
  ADMIN_SHARED_ID: {{ .Values.env.ADMIN_SHARED_ID | quote }}
  ADMIN_SHARED_EMAIL: {{ .Values.env.ADMIN_SHARED_EMAIL | quote }}
  STORE_BOLT_PATH: {{ .Values.env.STORE_BOLT_PATH | quote }}
  BACKUP_PATH: {{ .Values.env.BACKUP_PATH | quote }}
  IMAGE_MAX_SIZE: {{ .Values.env.IMAGE_MAX_SIZE | quote }}
  SECRET: {{ .Values.env.SECRET | quote }}
  ADMIN_PASSWD: {{ .Values.env.ADMIN_PASSWD | quote }}
