include:
  - global.common.bashrc
  - global.common.ca
  - global.common.exporters
  - global.common.hostname
  - global.common.hosts
  - global.common.motd
  - global.common.host_type
  - global.common.network
  - global.common.packages
  - global.common.promtail
  - global.common.salt-minion
  - global.common.sources
  - global.common.ssh
  - global.common.users
