apiVersion: v2
name: images-khaddict
description: A Helm chart for images.khaddict.com
type: application
version: 0.1.0
appVersion: "9d56eb3"
home: https://github.com/khaddict/voidnode
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/images.khaddict.com
maintainers:
  - name: platform
