# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: util/json.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'util/json.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0futil/json.proto\x12\x08\x42SB_Util\"@\n\x04Json\x12*\n\x0b\x63ompression\x18\x01 \x01(\x0e\x32\x15.BSB_Util.Compression\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*\"\n\x0b\x43ompression\x12\t\n\x05PLAIN\x10\x00\x12\x08\n\x04GZIP\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'util.json_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPRESSION']._serialized_start=95
  _globals['_COMPRESSION']._serialized_end=129
  _globals['_JSON']._serialized_start=29
  _globals['_JSON']._serialized_end=93
# @@protoc_insertion_point(module_scope)
