# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/ble.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state/ble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstate/ble.proto\x12\rBSB_State.Ble\"c\n\x03\x42le\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.BSB_State.Ble.ServiceStatus\x12\x1b\n\x0eremote_address\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_remote_address*u\n\rServiceStatus\x12\t\n\x05RESET\x10\x00\x12\x12\n\x0eINITIALIZATION\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0f\n\x0b\x41\x44VERTISING\x10\x03\x12\x0f\n\x0b\x43ONNECTABLE\x10\x04\x12\r\n\tCONNECTED\x10\x05\x12\t\n\x05\x45RROR\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.ble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICESTATUS']._serialized_start=135
  _globals['_SERVICESTATUS']._serialized_end=252
  _globals['_BLE']._serialized_start=34
  _globals['_BLE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
