# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/brightness.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state/brightness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16state/brightness.proto\x12\tBSB_State\"\x15\n\x13\x42rightnessAutomatic\"&\n\x10\x42rightnessManual\x12\x12\n\nbrightness\x18\x01 \x01(\r\"\x96\x01\n\nBrightness\x12\x33\n\tautomatic\x18\x01 \x01(\x0b\x32\x1e.BSB_State.BrightnessAutomaticH\x00\x12-\n\x06manual\x18\x02 \x01(\x0b\x32\x1b.BSB_State.BrightnessManualH\x00\x12\x19\n\x11\x61\x63tual_brightness\x18\x03 \x01(\rB\t\n\x07settingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.brightness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRIGHTNESSAUTOMATIC']._serialized_start=37
  _globals['_BRIGHTNESSAUTOMATIC']._serialized_end=58
  _globals['_BRIGHTNESSMANUAL']._serialized_start=60
  _globals['_BRIGHTNESSMANUAL']._serialized_end=98
  _globals['_BRIGHTNESS']._serialized_start=101
  _globals['_BRIGHTNESS']._serialized_end=251
# @@protoc_insertion_point(module_scope)
