# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/matter.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state/matter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12state/matter.proto\x12\tBSB_State\"c\n\x18MatterCommissioningState\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.BSB_State.MatterCommissioningStatus\x12\x11\n\ttimestamp\x18\x02 \x01(\x06\"R\n\x06Matter\x12\x14\n\x0c\x66\x61\x62ric_count\x18\x01 \x01(\r\x12\x32\n\x05state\x18\x02 \x01(\x0b\x32#.BSB_State.MatterCommissioningState*c\n\x19MatterCommissioningStatus\x12\x11\n\rNEVER_STARTED\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x1a\n\x16\x43OMPLETED_SUCCESSFULLY\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.matter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATTERCOMMISSIONINGSTATUS']._serialized_start=218
  _globals['_MATTERCOMMISSIONINGSTATUS']._serialized_end=317
  _globals['_MATTERCOMMISSIONINGSTATE']._serialized_start=33
  _globals['_MATTERCOMMISSIONINGSTATE']._serialized_end=132
  _globals['_MATTER']._serialized_start=134
  _globals['_MATTER']._serialized_end=216
# @@protoc_insertion_point(module_scope)
