# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/power.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state/power.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11state/power.proto\x12\tBSB_State\"\x13\n\x11UnknownPowerState\"\xae\x01\n\nPowerState\x12\x30\n\x0e\x62\x61ttery_status\x18\x01 \x01(\x0e\x32\x18.BSB_State.BatteryStatus\x12\x1e\n\x16\x62\x61ttery_charge_percent\x18\x02 \x01(\r\x12\x1a\n\x12\x62\x61ttery_voltage_mv\x18\x03 \x01(\r\x12\x1a\n\x12\x62\x61ttery_current_ma\x18\x04 \x01(\x11\x12\x16\n\x0eusb_voltage_mv\x18\x05 \x01(\r\"i\n\x05Power\x12/\n\x07unknown\x18\x01 \x01(\x0b\x32\x1c.BSB_State.UnknownPowerStateH\x00\x12&\n\x05known\x18\x02 \x01(\x0b\x32\x15.BSB_State.PowerStateH\x00\x42\x07\n\x05state*;\n\rBatteryStatus\x12\x0f\n\x0b\x44ISCHARGING\x10\x00\x12\x0c\n\x08\x43HARGING\x10\x01\x12\x0b\n\x07\x43HARGED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.power_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTERYSTATUS']._serialized_start=337
  _globals['_BATTERYSTATUS']._serialized_end=396
  _globals['_UNKNOWNPOWERSTATE']._serialized_start=32
  _globals['_UNKNOWNPOWERSTATE']._serialized_end=51
  _globals['_POWERSTATE']._serialized_start=54
  _globals['_POWERSTATE']._serialized_end=228
  _globals['_POWER']._serialized_start=230
  _globals['_POWER']._serialized_end=335
# @@protoc_insertion_point(module_scope)
