# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/wifi.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'state/wifi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10state/wifi.proto\x12\tBSB_State\"\x12\n\x10WifiStateUnknown\"\x13\n\x11WifiStateInactive\"\xa9\x01\n\x0fWifiStateActive\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.BSB_State.WifiConnectionStatus\x12\x0c\n\x04ssid\x18\x02 \x01(\t\x12\r\n\x05\x62ssid\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\r\x12\x0c\n\x04rssi\x18\x05 \x01(\x11\x12)\n\x08security\x18\x06 \x01(\x0e\x32\x17.BSB_State.WifiSecurity\"\x99\x01\n\tIpAddress\x12\'\n\x08protocol\x18\x01 \x01(\x0e\x32\x15.BSB_State.IpProtocol\x12\x30\n\x06method\x18\x02 \x01(\x0e\x32 .BSB_State.IpConfigurationMethod\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0f\n\x07gateway\x18\x04 \x01(\t\x12\x0f\n\x07netmask\x18\x05 \x01(\t\"\xd0\x01\n\x04Wifi\x12.\n\x07unknown\x18\x01 \x01(\x0b\x32\x1b.BSB_State.WifiStateUnknownH\x00\x12\x30\n\x08inactive\x18\x02 \x01(\x0b\x32\x1c.BSB_State.WifiStateInactiveH\x00\x12,\n\x06\x61\x63tive\x18\x03 \x01(\x0b\x32\x1a.BSB_State.WifiStateActiveH\x00\x12*\n\x0cip_addresses\x18\x04 \x03(\x0b\x32\x14.BSB_State.IpAddressB\x0c\n\nwifi_state*Z\n\x14WifiConnectionStatus\x12\r\n\tCONNECTED\x10\x00\x12\x0e\n\nCONNECTING\x10\x01\x12\x11\n\rDISCONNECTING\x10\x02\x12\x10\n\x0cRECONNECTING\x10\x03*h\n\x0cWifiSecurity\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\x07\n\x03WPA\x10\x02\x12\x08\n\x04WPA2\x10\x03\x12\x07\n\x03WEP\x10\x04\x12\x0c\n\x08WPA_WPA2\x10\x05\x12\x08\n\x04WPA3\x10\x06\x12\r\n\tWPA2_WPA3\x10\x07*-\n\x15IpConfigurationMethod\x12\x08\n\x04\x44HCP\x10\x00\x12\n\n\x06STATIC\x10\x01* \n\nIpProtocol\x12\x08\n\x04IPV4\x10\x00\x12\x08\n\x04IPV6\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.wifi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICONNECTIONSTATUS']._serialized_start=611
  _globals['_WIFICONNECTIONSTATUS']._serialized_end=701
  _globals['_WIFISECURITY']._serialized_start=703
  _globals['_WIFISECURITY']._serialized_end=807
  _globals['_IPCONFIGURATIONMETHOD']._serialized_start=809
  _globals['_IPCONFIGURATIONMETHOD']._serialized_end=854
  _globals['_IPPROTOCOL']._serialized_start=856
  _globals['_IPPROTOCOL']._serialized_end=888
  _globals['_WIFISTATEUNKNOWN']._serialized_start=31
  _globals['_WIFISTATEUNKNOWN']._serialized_end=49
  _globals['_WIFISTATEINACTIVE']._serialized_start=51
  _globals['_WIFISTATEINACTIVE']._serialized_end=70
  _globals['_WIFISTATEACTIVE']._serialized_start=73
  _globals['_WIFISTATEACTIVE']._serialized_end=242
  _globals['_IPADDRESS']._serialized_start=245
  _globals['_IPADDRESS']._serialized_end=398
  _globals['_WIFI']._serialized_start=401
  _globals['_WIFI']._serialized_end=609
# @@protoc_insertion_point(module_scope)
