namespace: khaddict

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 80

httproute:
  gatewayName: envoy-gateway

sites:
  - name: www
    replicas: 2
    image:
      repository: nginx
      tag: "1.31.2"
    host: www.khaddict.lab
    hasSitemap: true
    livenessInitialDelaySeconds: 15
  - name: blog
    replicas: 2
    image:
      repository: nginx
      tag: "1.31.2"
    host: blog.khaddict.lab
    hasSitemap: false
    livenessInitialDelaySeconds: 15
  - name: images
    replicas: 2
    image:
      repository: ghcr.io/khaddict/images-khaddict
      tag: 5f0698a
    host: images.khaddict.lab
    hasSitemap: false
    livenessInitialDelaySeconds: 5
  - name: projects
    replicas: 2
    image:
      repository: nginx
      tag: "1.31.2"
    host: projects.khaddict.lab
    hasSitemap: false
    livenessInitialDelaySeconds: 15
