apiVersion: v2
name: changedetection
description: A Helm chart for changedetection
type: application
version: 0.1.0
# renovate: depName=dgtlmoon/changedetection.io datasource=docker registryUrl=https://ghcr.io
appVersion: "0.60.4"
home: https://github.com/khaddict/voidnode
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/changedetection
maintainers:
  - name: platform
