app: changedetection
namespace: changedetection

deployment:
  replicas: 1
  image: ghcr.io/dgtlmoon/changedetection.io:latest
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

service:
  name: changedetection
  type: ClusterIP
  port: 5000
  targetPort: 5000
  protocol: TCP

httproute:
  host: changedetection.khaddict.lab
  gatewayName: envoy-gateway

pvc:
  storage: 5Gi
