apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn-backup-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY: {{ .Values.auth.accessKey | quote }}
  SECRET_KEY: {{ .Values.auth.secretKey | quote }}
