apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-rclone-conf
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn-backup-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  rclone.conf: |
    [{{ .Values.rclone.remote }}]
    type = webdav
    url = {{ .Values.rclone.kdriveUrl }}
    vendor = other
    user = {{ .Values.rclone.kdriveUser }}
    pass = {{ .Values.rclone.kdrivePassword }}
