apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn-backup-bridge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "longhorn-backup-bridge.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
