apiVersion: v2
name: cilium
description: A Helm chart for cilium
type: application
version: 0.1.0
appVersion: "1.18.2"
home: https://cilium.io
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/cilium
  - https://github.com/cilium/cilium
maintainers:
  - name: platform
dependencies:
  - name: cilium
    version: 1.18.2
    repository: https://helm.cilium.io/
