apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: voidnode
    app.kubernetes.io/component: system
  annotations:
    owner: platform
    repo: khaddict/voidnode
spec:
  project: default
  source:
    repoURL: https://github.com/khaddict/voidnode.git
    targetRevision: main
    path: argocd/apps/local-path-provisioner
    helm:
      releaseName: local-path-storage
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true