apiVersion: v2
name: uptime-kuma
description: A Helm chart for uptime-kuma
type: application
version: 0.1.0
appVersion: "2"
home: https://github.com/khaddict/voidnode
sources:
  - https://github.com/khaddict/voidnode/tree/main/argocd/apps/uptime-kuma
maintainers:
  - name: platform

