app: uptime-kuma
namespace: uptime-kuma

deployment:
  replicas: 1
  image: louislam/uptime-kuma:2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

service:
  name: uptime-kuma
  type: ClusterIP
  port: 3001
  targetPort: 3001
  protocol: TCP

probes:
  enabled: false
  liveness:
    httpGet:
      path: /
      port: 3001
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: 3001
    initialDelaySeconds: 10
    periodSeconds: 5

httproute:
  host: uptimekuma.khaddict.lab
  gatewayName: envoy-gateway

pvc:
  storage: 10Gi
  storageClassName: local-path
