apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: changedetection
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khaddict/voidnode.git
    targetRevision: HEAD
    path: argocd/apps/changedetection
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: changedetection
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
