apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: voidnode
    app.kubernetes.io/component: service
  annotations:
    owner: platform
    repo: khaddict/voidnode
spec:
  project: default
  source:
    repoURL: https://github.com/khaddict/voidnode.git
    targetRevision: main
    path: argocd/apps/uptime-kuma
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
