apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-images
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "site-khaddict.labels" . | nindent 4 }}
binaryData:
  khazix_pc.png: {{ .Files.Get "images/khazix_pc.png" | b64enc }}
